//Criando uma Rota
POST http://localhost:3333/mangas
Content-Type: application/json

{
    "titulo": "Manga 01",
    "autor": "Autor 01",
    "npaginas": 100
}

###
//Fazendo uma pesquisa com o search
GET http://localhost:3333/mangas?search=Manga 02


###
//Criando e listando livros
GET http://localhost:3333/mangas

###
//Atualizando o livro cadastrado
PUT http://localhost:3333/mangas/
Content-Type: application/json

{
    "titulo": "Manga 02",
    "autor": "Autor 02",
    "npaginas": 100
}


###
//Deletando o livro cadastrado
DELETE http://localhost:3333/mangas/